/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/': RouteRecordInfo<
      '/demos/',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/animating-crosses': RouteRecordInfo<
      '/demos/animating-crosses',
      '/demos/animating-crosses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/basic': RouteRecordInfo<
      '/demos/basic',
      '/demos/basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/composite': RouteRecordInfo<
      '/demos/composite',
      '/demos/composite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/high-res-drawing': RouteRecordInfo<
      '/demos/high-res-drawing',
      '/demos/high-res-drawing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/pdf-watermark': RouteRecordInfo<
      '/demos/pdf-watermark',
      '/demos/pdf-watermark',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/playground': RouteRecordInfo<
      '/demos/playground',
      '/demos/playground',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/shapes': RouteRecordInfo<
      '/demos/shapes',
      '/demos/shapes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/text-playground': RouteRecordInfo<
      '/demos/text-playground',
      '/demos/text-playground',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/': RouteRecordInfo<
      '/docs/',
      '/docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/demos/index.vue': {
      routes:
        | '/demos/'
      views:
        | never
    }
    'src/pages/demos/animating-crosses.vue': {
      routes:
        | '/demos/animating-crosses'
      views:
        | never
    }
    'src/pages/demos/basic.vue': {
      routes:
        | '/demos/basic'
      views:
        | never
    }
    'src/pages/demos/composite.vue': {
      routes:
        | '/demos/composite'
      views:
        | never
    }
    'src/pages/demos/high-res-drawing.vue': {
      routes:
        | '/demos/high-res-drawing'
      views:
        | never
    }
    'src/pages/demos/pdf-watermark.vue': {
      routes:
        | '/demos/pdf-watermark'
      views:
        | never
    }
    'src/pages/demos/playground.vue': {
      routes:
        | '/demos/playground'
      views:
        | never
    }
    'src/pages/demos/shapes.vue': {
      routes:
        | '/demos/shapes'
      views:
        | never
    }
    'src/pages/demos/text-playground.vue': {
      routes:
        | '/demos/text-playground'
      views:
        | never
    }
    'src/pages/docs/index.vue': {
      routes:
        | '/docs/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
